seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: 'D5_M5_F5_slope5_{epoch}-{step}-{val_ExpRate:.4f}'
  # gpus: 1
  gpus: 1
  accelerator: gpu
  check_val_every_n_epoch: 5
  max_epochs: 310
  deterministic: true
  resume_from_checkpoint: null
model:
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  MHA_dropout: 0.3
  FFN_dropout: 0.3
  densenet_dropout: 0.2
  dc: 32
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.08
  patience: 8
data:
  zipfile_path: data.zip
  test_year: 'all'
  train_batch_size: 64
  eval_batch_size: 32
  num_workers: 4
  scale_aug: true
curriculum:
  dropout:
    type: 'sigmoid'
    slope: 10 # from 1 to 10
    mha: true
    mha_start_dropout: 0.0
    mha_end_dropout: 0.5
    ffn: true
    ffn_start_dropout: 0.0
    ffn_end_dropout: 0.5
    densenet: true
    densenet_start_dropout: 0.0
    densenet_end_dropout: 0.5
  learning:
    type: "Vanilla"
    pacing_epoch: 50
  blur:
    sigma: 1.0



    
    
    